const BAD_REQUEST_ERROR = 'Bad Request'
const UNAUTHORIZED_ERROR = 'Unauthorized'
const NOT_FOUND_ERROR = 'Not Found'
const CONFLICT_ERROR = 'Conflict'
const INVALID_CREDENTIALS_ERROR = 'Invalid credentials'
const USER_ALREADY_EXISTS_ERROR = 'User already exists'
const NO_REFRESH_TOKEN_ERROR = 'No refresh token'
const INVALID_REFRESH_TOKEN_ERROR = 'Invalid refresh token'
const INVALID_TOKEN_ERROR = 'Invalid token'

const SUCCESS_200 = 200
const SUCCESS_201 = 201
const SUCCESS_204 = 204

const ERROR_400 = 400
const ERROR_401 = 401
const ERROR_404 = 404
const ERROR_409 = 409
const ERROR_500 = 500

const INTERNAL_SERVER_ERROR = 'Internal Server Error'

export {
  BAD_REQUEST_ERROR,
  CONFLICT_ERROR,
  ERROR_400,
  ERROR_401,
  ERROR_404,
  ERROR_409,
  ERROR_500,
  INTERNAL_SERVER_ERROR,
  INVALID_CREDENTIALS_ERROR,
  INVALID_REFRESH_TOKEN_ERROR, INVALID_TOKEN_ERROR, NO_REFRESH_TOKEN_ERROR,
  NOT_FOUND_ERROR,
  SUCCESS_200,
  SUCCESS_201,
  SUCCESS_204,
  UNAUTHORIZED_ERROR,
  USER_ALREADY_EXISTS_ERROR
}

